### ISSUE TITLE
Add events?

### ISSUE THREAD

**Issue by krionical** [mark-when/c2#1]
After running npm run-script dev I get a pretty page with events on them from someone's life who is probably an example of data. Where do I add events that are not example data?

**Comment by krionical** [comment]
Is it through the markwhen plugin in VS?

**Comment by kochrt** [comment]
The VS code extension doesn’t yet support custom views - you can go to
app.markwhen.com, go to settings, then visualizations, then scroll down and
select add new visualization and set the url to http://localhost:5150. Add
dummy stuff for the other fields (id, author, etc)

**Comment by krionical** [comment]
Ah gotcha. Thanks for clearing that up!
